version: "3"

services:
  database-assignment:
    image: postgres:alpine
    restart: always
    expose:
      - 1132
    ports:
      - "1132:5432"
    volumes:
      - assignmentdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=assignment-service
  app-assignment:
    build:
      context: ./../assignment_service/ # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: assignment_service
    expose:
      - 1100
      - 1101
    ports:
      - "1100:1100"
      - "1101:1101"
    depends_on:
      - database-assignment
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-assignment:5432/assignment-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-assignment:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "assignment_service",
      "--app-port", "1101",
      "--dapr-http-port", "1100",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../assignment_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-assignment
      - redis
    network_mode: "service:app-assignment"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  assignmentdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true