services:
  database:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../assignment_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_ASSIGNMENT_SERVICE=assignment_service
  app-assignment:
    build:
      context: ./../assignment_service/ # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: assignment_service
    expose:
      - 1100
      - 1101
    ports:
      - "1100:1100"
      - "1101:1101"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/assignment_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-assignment:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "assignment_service",
      "--app-port", "1101",
      "--dapr-http-port", "1100",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../assignment_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-assignment
      - redis
    network_mode: "service:app-assignment"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true