# Database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:1132/${database_name}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.sql.init.continue-on-error=true
spring.jpa.hibernate.ddl-auto=update

course_service.url=${COURSE_SERVICE_URL:http://app-course:2001/graphql}
content_service.url=${CONTENT_SERVICE_URL:http://app-content:4001/graphql}
user_service.url=${USER_SERVICE_URL:http://app-user:5001/graphql}

ollama.url=${OLLAMA_URL:http://129.69.217.245:4000}
ollama.endpoint=${OLLAMA_ENDPOINT:v1/chat/completions}
ollama.model=${OLLAMA_MODEL:qwen3-coder-80B-A10B}
ollama.promptFolder=${OLLAMA_PROMPT_FOLDER:prompt_templates}
ollama.apiKey=${OLLAMA_API_KEY:}